### ISSUE TITLE
Fleet Carrier Commander Timer

### ISSUE THREAD

**Issue by StanleyXenon** [fredjk-gh/ObservatoryPlugins#4]
Hi
Enjoying the plugin.  Minor issue is that the Countdown timer on teh App doesn't match teh actual jump timer on Elite dangerous

Currently plugin shows 14min jump countdown vs 16min within elite

Would it be possible to save the route rather than needing to create it every time you restart Observatory? (I'm currently part way through a 75 jump sequence which obv takes multiple days)

**Comment by fredjk-gh** [comment]
Sorry for the slow response -- I was away on vacation. I'm glad you're enjoying the plugin!

Regarding the countdown timer: This is likely do to drift of your system clock vs. Elite Dangerous game time. If you see this, consider syncing your system clock. Instructions for how to do this on [Windows 10](https://answers.microsoft.com/en-us/windows/forum/all/how-to-force-windows-10-time-to-synch-with-a-time/20f3b546-af38-42fb-a2d0-d4df13cc8f43).

Regarding the route: The plugin should save the route in a json file in the plugins data directory and that should survive restarts of the app. If the app knows about your commander(s) and carrier(s) at start up, it should also know the route. Can you confirm it remembers the commander(s) and carrier(s)? Are you doing a read-all everytime you start Observatory?

o7

**Comment by StanleyXenon** [comment]
Hi there

 

Sorry for the slow reply back, I took some time away

 

Just to let you know.  The countdown timer was fixed by syncing the clock as per your suggestion.

 

The route issue not being saved has also been solved, by not doing a read all on start up – I must have enabled that setting with all the messing about I had to do after updating Observatory and dealing with it’s nonsense. In the end I gave up and rolled it back.  It’s only your plug in and Bio insights which has me still using the program

 

Thanks again for you help and support

 

O7

**Comment by fredjk-gh** [comment]
I'm sorry to hear you had issues updating Observatory. That said, if you need more support, you can join us on discord (https://discord.gg/9fRv4t7q) and we can hopefully help you in more realtime there.

Since your questions are solved, I'm going to close out the issue. o7!
